[package]
name = "hosts2unbound"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^ 0.3"
failure = "^ 0.1"
reqwest = { version = "^ 0.10", features = [ "blocking" ] }
